version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: epldb

  player-statistics-service:
    build:
      context: ./player-statistics-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=epldb

  team-statistics-service:
    build:
      context: ./team-statistics-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - player-statistics-service
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=team_statistics_db
      - PLAYER_SERVICE_URL=http://player-statistics-service:8080

volumes:
  mongodb_data: