apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Aasim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: team-statistics-service
  name: team-statistics-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: team-statistics-service
status:
  loadBalancer: {}
