apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Aasim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: team-statistics-service
  name: team-statistics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: team-statistics-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Aasim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/epl-insights-distributed-system-default: "true"
        io.kompose.service: team-statistics-service
    spec:
      containers:
        - env:
            - name: PLAYER_SERVICE_URL
              value: http://player-statistics-service:8080
            - name: SPRING_DATA_MONGODB_DATABASE
              value: team_statistics_db
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
          image: aasim7/epl-insights-distributed-system-team-statistics-service:latest
          name: team-statistics-service
          ports:
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
